### ISSUE TITLE
Réparation et configurations des liens internes

### ISSUE THREAD

**Issue by Posoroko** [Six-lits-cone-valet/P-pites#17]
La nav bar et le footer présentent des liens internes vers les différentes pages du site.

Certains de ces liens ne fonctionnent pas.

il faudrait:

1 - ne conserver que les liens vers les pages de la phase A
2 - S'assurer que tous les fichiers du dossier /pages portent un nom en français
3 - S'assurer que le nom du lien et le nom de la page vers laquelle il pointe soient identiques
4 - Vérifier que tous les liens fonctionnent
5 - Ajouter un h1 sur toutes les pages pour indiquer (temporairement) le nom de la page sur laquelle on se trouve

**Comment by Coranet** [comment]
Bien reçu

**Comment by Coranet** [comment]
Tout semble ok, sauf les liens de la navbar que je n'arrive pas à faire fonctionner, et qui ne fonctionnaient déjà pas chez moi

**Comment by Posoroko** [comment]
LEs liens de la nav bar n'ont jamais fonctionné je crois.  Tu n'as pas ouvert une PR, tu as ouvert une nouvelle issue.  Je ne peux donc pas voir ton code....
