### ISSUE TITLE
Photos pour les villes dans le Directus

### ISSUE THREAD

**Issue by Posoroko** [Six-lits-cone-valet/P-pites#21]
Ajouter une photo pour chaque ville de la collection Cities.

Pour l'instant, on peut mettre une photo trouvée sur google images et plus tard on les remplacera par des photos qu'on prendra nous même.

**Comment by Coranet** [comment]
Ok

**Comment by Coranet** [comment]
J'ai bien ajouté les photos vendredi pour les villes et même une description. Tout est ok dans les changements sauf l'affichage des photos que je n'arrive pas à faire apparaître.
