### ISSUE TITLE
Bouton et page connection

### ISSUE THREAD

**Issue by Posoroko** [Six-lits-cone-valet/P-pites#29]
Créer dabord  la page connection dans le dossier pages.

Ensuite, dans la navBar, ajouter le bouton (<NuxtLink /> ) pour se rendre à cette nouvelle page.

Pour le bouton, il faut  créer un composant qui sera importé dans NavBarMain.
Dans le composant, créer une variable "currentUser".  Cette variable servira à tester le bouton en attendant l'intégration du vrai sustème de connection des utilisateurs.
Si currentUser a une valeur, le boutoon affiche "déconnection".  Si currentUser est égal à null, le bouton affiche "connextion".

Donc, "connection" est un lien vers la page /connection, et "déconnection" est un simple bouton qui appelle la fonction "deconnectUser".
Tu peu créer cette fonction et juste lui faire faire un console.log en attendant l'implentation de la vrai fonctionnalité.

Sur la page /connection, ajouter un titre pour bien identifier la page. 
La prochaine étape sera de créer le formulaire de connection er de création de compte.

**Comment by Coranet** [comment]
Bouton 'connexion' crée mais le console.log 'deconnexion' n'apparaît pas.
