### ISSUE TITLE
Nouveau filtre pour les pépites

### ISSUE THREAD

**Issue by Posoroko** [Six-lits-cone-valet/P-pites#4]
Dans la collecttion Pepites (Directus), ajouter un menu déroulant avec les options suivantes:
Cette issue ne sera pas liée à une pull request, les changements n'affecteront que la base de donnée (Directus)

nom du champ: diet
options: 
    -text: Vévétalien, value: vegan
    -text: Végétarien, value: vedgy
    -text: Carnivore, value: meaty

**Comment by Coranet** [comment]
Ok, je n'avais pas vu ça, je commence à comprendre comment communiquer avec github, je fais ça demain. Merci !

**Comment by Posoroko** [comment]
Filters were added to Directus
